branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - test
          - build
          - docs
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      required_signatures: true
      required_linear_history: true
      allow_fork_syncing: true 