branch_protection_rules:
  - pattern: main
    required_status_checks:
      strict: true
      contexts:
        - "Security Scan"
        - "Test Suite"
        - "CodeQL"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    enforce_admins: true
    required_signatures: true
    allow_force_pushes: false
    allow_deletions: false
    required_conversation_resolution: true 