name: Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust pytest-benchmark

    - name: Run performance tests
      run: |
        pytest tests/performance --benchmark-only
        locust -f tests/performance/locustfile.py --headless -u 100 -r 10 -t 1m

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: |
          .benchmarks/
          locust_results/

    - name: Check for performance regression
      run: |
        python scripts/check_performance.py
      env:
        PERFORMANCE_THRESHOLD: 1.1  # 10% degradation threshold 